# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0004_auto_20170325_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='duoshuo_comments',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='duoshuo_shortname',
        ),
        migrations.AddField(
            model_name='setting',
            name='comments',
            field=models.BooleanField(default=False, help_text='Enable comments', verbose_name='Comments'),
        ),
    ]
