# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-10 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
    ]
