# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-04 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('descriptor', models.CharField(max_length=255, verbose_name='Descriptor')),
                ('subtype', models.CharField(max_length=255, verbose_name='Subtype')),
                ('platform', models.CharField(max_length=255, verbose_name='Platform')),
                ('icon', models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='icons', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
            },
        ),
        migrations.CreateModel(
            name='OSVersion',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('descriptor', models.CharField(max_length=255, verbose_name='Version')),
                ('build', models.CharField(max_length=255, verbose_name='Build')),
                ('icon', models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='icons', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'iOS Version',
                'verbose_name_plural': 'iOS Versions',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('icon', models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='icons', verbose_name='Icon')),
                ('package', models.CharField(help_text='Example: com.darwindev.xxtouch', max_length=255, unique=True, verbose_name='Package')),
                ('author_name', models.CharField(max_length=255, verbose_name='Author')),
                ('author_email', models.EmailField(blank=True, max_length=255, verbose_name='Author Email')),
                ('maintainer_name', models.CharField(max_length=255, verbose_name='Maintainer')),
                ('maintainer_email', models.EmailField(blank=True, max_length=255, verbose_name='Maintainer Email')),
                ('sponsor_name', models.CharField(max_length=255, verbose_name='Sponsor')),
                ('sponsor_email', models.EmailField(blank=True, max_length=255, verbose_name='Sponsor Email')),
                ('depiction', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('origin', models.CharField(help_text='This name will be displayed in the sources interface of Cydia.', max_length=255, verbose_name='Origin')),
                ('label', models.CharField(help_text='This name will be displayed at the top of the package list interface.', max_length=255, verbose_name='Label')),
                ('codename', models.CharField(max_length=255, verbose_name='Codename')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='0.0.1-1', help_text='Example: 0.0.1-1', max_length=255, verbose_name='Version')),
                ('icon', models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='icons', verbose_name='Repository Icon')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('icon', models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='icons', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('download_times', models.IntegerField(default=0, editable=False, verbose_name='Download Times')),
                ('storage', models.FileField(help_text='Choose a Debain Package (*.deb) to upload', upload_to='versions', verbose_name='Storage')),
                ('md5', models.CharField(editable=False, max_length=32, verbose_name='MD5')),
                ('sha1', models.CharField(editable=False, max_length=40, verbose_name='SHA1')),
                ('sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA256')),
                ('size', models.BigIntegerField(default=0, editable=False, verbose_name='Size')),
                ('package', models.CharField(editable=False, help_text='Example: com.darwindev.xxtouch', max_length=255, verbose_name='Package')),
                ('version', models.CharField(default='0.0.1-1', help_text='Example: 0.0.1-1', max_length=255, verbose_name='Version')),
                ('update_logs', models.TextField(blank=True, null=True)),
                ('device_compatibility', models.ManyToManyField(blank=True, to='WEIPDCRM.DeviceType')),
                ('os_compatibility', models.ManyToManyField(blank=True, to='WEIPDCRM.OSVersion')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEIPDCRM.Section'),
        ),
    ]
