# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cache_time',
            field=models.IntegerField(default=3600, help_text='Minimum rendering interval, in seconds.', verbose_name='Cache Time'),
        ),
        migrations.AddField(
            model_name='setting',
            name='enable_cache',
            field=models.BooleanField(default=False, help_text="Save the rendered results of all frontend pages so that the server don't have to perform the calculation each time.", verbose_name='Enable Cache'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='icon',
            field=models.FileField(blank=True, help_text='Choose an Icon (*.png) to upload', max_length=255, null=True, upload_to='device-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='icon',
            field=models.FileField(blank=True, help_text='Choose an Icon (*.png) to upload', max_length=255, null=True, upload_to='os-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='release',
            name='icon',
            field=models.FileField(blank=True, help_text='Choose an Icon (*.png) to upload', max_length=255, null=True, upload_to='repository-icons', verbose_name='Repository Icon'),
        ),
        migrations.AlterField(
            model_name='version',
            name='online_icon',
            field=models.FileField(blank=True, help_text='Choose an Icon (*.png) to upload', max_length=255, null=True, upload_to='package-icons', verbose_name='Online Icon'),
        ),
    ]
