# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='active_release',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WEIPDCRM.Release', verbose_name='Active Release'),
        ),
        migrations.AlterField(
            model_name='build',
            name='details',
            field=models.TextField(blank=True, default='', help_text='Tell others what did you do this time before you rebuild the repository.', null=True, verbose_name='Details'),
        ),
    ]
