# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screenshot',
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='descriptor',
            field=models.CharField(help_text='Example: iPhone 7 Plus', max_length=255, verbose_name='Descriptor'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='icon',
            field=models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='device-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='platform',
            field=models.CharField(help_text='Example: A1661/A1784/A1785', max_length=255, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='subtype',
            field=models.CharField(help_text='Example: iPhone9,2', max_length=255, verbose_name='Subtype'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='build',
            field=models.CharField(help_text='Example: 14C92', max_length=255, verbose_name='Build'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='descriptor',
            field=models.CharField(help_text='Example: 10.2', max_length=255, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='icon',
            field=models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='os-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='package',
            name='icon',
            field=models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='package-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='release',
            name='icon',
            field=models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='repository-icons', verbose_name='Repository Icon'),
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', upload_to='section-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='version',
            name='storage',
            field=models.FileField(help_text='Choose a Debain Package (*.deb) to upload', upload_to='debs', verbose_name='Storage'),
        ),
    ]
