# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('compression', models.IntegerField(choices=[(0, 'Plain'), (1, 'Gzip'), (2, 'Plain and Gzip'), (3, 'Bzip'), (4, 'Plain and Bzip'), (5, 'Gzip and Bzip'), (6, 'All (Recommended)')], default=6, verbose_name='Packages Compression')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('active_release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WEIPDCRM.Release', verbose_name='Active Release')),
            ],
            options={
                'verbose_name': 'Build',
                'verbose_name_plural': 'Builds',
            },
        ),
    ]
