# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:06
from __future__ import unicode_literals

import WEIPDCRM.models.section
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ('-created_at',), 'verbose_name': 'Build', 'verbose_name_plural': 'Builds'},
        ),
        migrations.AddField(
            model_name='setting',
            name='duoshuo_comments',
            field=models.BooleanField(default=False, help_text='Enable DuoShuo comments feature', verbose_name='DuoShuo Comments'),
        ),
        migrations.AddField(
            model_name='setting',
            name='duoshuo_shortname',
            field=models.CharField(default='', help_text='Please go to %s for get short name (registration required)', max_length=255, verbose_name='DuoShuo Short Name'),
        ),
        migrations.AlterField(
            model_name='build',
            name='active_release',
            field=models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='WEIPDCRM.Release', verbose_name='Active Release'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='This is a general field that gives the package a category based on the software that it installs. You will not be able to edit its name after assigning any package under it.', max_length=255, unique=True, validators=[WEIPDCRM.models.section.validator_underscore], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='redirect_resources',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Moved'), (2, 'Accel')], default=0, help_text='None - Read resources and return.<br />Moved - Return 301/302 responses and redirect to the real resource urls.<br />Accel - Redirect resource requests to WEB servers without changing urls.', verbose_name='Redirect Methods'),
        ),
    ]
