# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('WEIPDCRM', '0002_auto_20170104_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('repository_url', models.URLField(help_text="Displayed on the homepage for the user to add, and used for the autofill package's Depiction when import.")),
            ],
            bases=('preferences.preferences',),
        ),
    ]
