# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0002_auto_20170325_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='weibo_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Weibo Name'),
        ),
        migrations.AddField(
            model_name='setting',
            name='weibo_url',
            field=models.URLField(max_length=128, null=True, verbose_name='Weibo URL'),
        ),
    ]
