# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0002_auto_20170310_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='duoshuo_shortname',
            field=models.CharField(default='', help_text='Please go to <a href="http://duoshuo.com/">http://duoshuo.com</a> for get short name (registration required)', max_length=255, verbose_name='DuoShuo Short Name'),
        ),
    ]
