# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 10:12
from __future__ import unicode_literals

import WEIPDCRM.models.version
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0002_auto_20170221_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='package',
            field=models.CharField(db_index=True, help_text='This is the "identifier" of the package. This should be, entirely in lower case, a reversed hostname (much like a "bundleIdentifier" in Apple\'s Info.plist files).', max_length=255, validators=[WEIPDCRM.models.version.validate_reversed_domain], verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='version',
            name='section',
            field=models.ForeignKey(blank=True, default=None, help_text='Under the "Install" tab in Cydia, packages are listed by "Section". If you would like to encode a space into your section name, use an underscore (Cydia will automatically convert these).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WEIPDCRM.Section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(db_index=True, default='1.0-1', help_text="A package's version indicates two separate values: the version of the software in the package, and the version of the package itself. These version numbers are separated by a hyphen.", max_length=255, validators=[WEIPDCRM.models.version.validate_version], verbose_name='Version'),
        ),
    ]
