# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0004_auto_20170325_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='alipay',
            new_name='alipay_url',
        ),
    ]
