# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0004_auto_20170104_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='advanced_mode',
            field=models.BooleanField(default='', help_text='Generate awesome depiction page for each version.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='repository_url',
            field=models.URLField(help_text="Displayed on the homepage for the user to add, and used for the autofill package's Depiction when import.Example 1: https://apt.82flex.com/Example 2: http://example.com/apt/"),
        ),
    ]
