# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0005_auto_20170325_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='qq_group_number',
            field=models.CharField(help_text='Show QQ Group link in mobile package info page', max_length=255, null=True, verbose_name='QQ Group Number'),
        ),
    ]
