# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0005_auto_20170105_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='downgrade_support',
            field=models.BooleanField(default=True, help_text='Enable this function will cause a long-term traffic consumption.'),
        ),
        migrations.AddField(
            model_name='setting',
            name='packages_compression',
            field=models.IntegerField(choices=[(0, 'plain'), (1, 'gzip'), (2, 'plain and gzip'), (3, 'bzip'), (4, 'plain and bzip'), (5, 'gzip and bzip'), (6, 'all')], default=6, help_text='Please change the compression method if error occurred when try to rebuild the list.'),
        ),
        migrations.AddField(
            model_name='setting',
            name='packages_validation',
            field=models.IntegerField(choices=[(0, 'No validation'), (1, 'MD5Sum'), (2, 'MD5Sum & SHA1'), (3, 'MD5Sum & SHA1 & SHA256')], default=1, help_text='It will not take effect until any version edited or added.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='advanced_mode',
            field=models.BooleanField(default=True, help_text='Check it to generate awesome depiction page for each version.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='repository_url',
            field=models.URLField(help_text='Displayed on the homepage for the user to add.<br />Example 1: https://apt.82flex.com/<br />Example 2: http://example.com/apt/'),
        ),
    ]
