# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0006_auto_20170325_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='alipay_url',
            field=models.URLField(help_text='Show donate via Alipay link in mobile package info page', max_length=255, null=True, verbose_name='Alipay URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='qq_group_number',
            field=models.URLField(help_text='Show QQ Group link in mobile package info page', max_length=255, null=True, verbose_name='QQ Group Number'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weibo_url',
            field=models.URLField(help_text='Show Weibo link in mobile package info page', max_length=255, null=True, verbose_name='Weibo URL'),
        ),
    ]
