# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0006_auto_20170105_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='keywords',
            field=models.CharField(default='', help_text='Separated by commas.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='release',
            name='codename',
            field=models.CharField(default='', max_length=255, verbose_name='Codename'),
        ),
        migrations.AlterField(
            model_name='release',
            name='label',
            field=models.CharField(default='', help_text='This name will be displayed at the top of the package list interface.', max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='release',
            name='origin',
            field=models.CharField(default='', help_text='This name will be displayed in the sources interface of Cydia.', max_length=255, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='repository_url',
            field=models.URLField(default=b'', help_text='Displayed on the homepage for the user to add.<br />Example 1: https://apt.82flex.com/<br />Example 2: http://example.com/apt/'),
        ),
    ]
