# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0007_auto_20170105_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='homepage',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='platform',
            field=models.CharField(blank=True, help_text='Example: A1661/A1784/A1785', max_length=255, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='package',
            name='depiction',
            field=models.URLField(blank=True, default='', help_text='Detail page related to this package.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Something about this package.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package',
            field=models.CharField(help_text='Unique identifier, Example: com.darwindev.xxtouch', max_length=255, unique=True, verbose_name='Package'),
        ),
    ]
