# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-10 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0009_auto_20170105_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='control_field',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
