# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0011_remove_setting_repository_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='sponsor_email',
        ),
        migrations.AddField(
            model_name='package',
            name='sponsor_site',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Sponsor Site'),
        ),
        migrations.AlterField(
            model_name='package',
            name='author_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Author Email'),
        ),
        migrations.AlterField(
            model_name='package',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='package',
            name='depiction',
            field=models.URLField(blank=True, default='', help_text='Detail page related to this package.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The format for the package description is a short brief summary on the first line (after the Description field). The following lines should be used as a longer, more detailed description.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='homepage',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='icon',
            field=models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', null=True, upload_to='package-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='package',
            name='maintainer_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Maintainer Email'),
        ),
        migrations.AlterField(
            model_name='package',
            name='maintainer_name',
            field=models.CharField(blank=True, help_text='It is typically the person who created the package, as opposed to the author of the software that was packaged.', max_length=255, null=True, verbose_name='Maintainer'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package',
            field=models.CharField(help_text='Unique identifier. The value of this field determines the package name, and is used to generate file names by most installation tools.<br />Example: com.darwindev.xxtouch', max_length=255, unique=True, verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sponsor'),
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', null=True, upload_to='section-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='This is a general field that gives the package a category based on the software that it installs.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(default='0.0.1-1', help_text="Typically, this is the original package's version number in whatever form the program's author uses. It may also include a Debian revision number (for non-native packages).<br />Example: 0.0.1-1", max_length=255, verbose_name='Version'),
        ),
    ]
