# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0012_auto_20170124_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='This is a general field that gives the package a category based on the software that it installs.', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
