# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0012_auto_20170326_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='display_social',
            field=models.BooleanField(default=False, help_text='Display social module', verbose_name='Display Social Module'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='alipay_url',
            field=models.URLField(blank=True, help_text='Show donate via Alipay link in mobile package info page', max_length=255, null=True, verbose_name='Alipay URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='copyright_name',
            field=models.CharField(blank=True, help_text='Corpyright name is displayed on the footer of the page, leave a blank will display the source name.', max_length=255, null=True, verbose_name='Copyright Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='copyright_year',
            field=models.PositiveIntegerField(blank=True, help_text='If input 2016, the final display is \xa9 2016-2017, leave a blank will display the current year.', null=True, verbose_name='Starting Year of Copyright'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='footer_icp',
            field=models.CharField(blank=True, help_text='ICP Number is displayed on the footer of the page.', max_length=255, null=True, verbose_name='ICP Number'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='qq_group_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='QQ Group Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='qq_group_url',
            field=models.URLField(blank=True, help_text='Show QQ Group link in mobile package info page.', max_length=255, null=True, verbose_name='QQ Group URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weibo_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Weibo Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weibo_url',
            field=models.URLField(blank=True, help_text='Show Weibo link in mobile package info page.', max_length=255, null=True, verbose_name='Weibo URL'),
        ),
    ]
