# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0013_auto_20170326_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='alipay_url',
            field=models.URLField(blank=True, help_text='Display "Donate via Alipay" link on the package info page.', max_length=255, null=True, verbose_name='Alipay URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='copyright_name',
            field=models.CharField(blank=True, help_text='Corpyright name is displayed on the footer, leave a blank will display the source name.', max_length=255, null=True, verbose_name='Copyright Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='copyright_year',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to display current year.', null=True, verbose_name='Starting Year of Copyright'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='display_social',
            field=models.BooleanField(default=False, help_text='Enable social module', verbose_name='Social Module'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='footer_icp',
            field=models.CharField(blank=True, help_text='The ICP Number displayed on the footer.', max_length=255, null=True, verbose_name='ICP Number'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='qq_group_url',
            field=models.URLField(blank=True, help_text='Display QQ group link on the package info page.', max_length=255, null=True, verbose_name='QQ Group URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weibo_url',
            field=models.URLField(blank=True, help_text='Display Weibo link on the package info page.', max_length=255, null=True, verbose_name='Weibo URL'),
        ),
    ]
