# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0013_auto_20170124_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='sha512',
            field=models.CharField(default='', max_length=128, verbose_name='SHA256'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='release',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='packages_validation',
            field=models.IntegerField(choices=[(0, 'No validation'), (1, 'MD5Sum'), (2, 'MD5Sum & SHA1'), (3, 'MD5Sum & SHA1 & SHA256'), (4, 'MD5Sum & SHA1 & SHA256 & SHA512')], default=1, help_text='It will not take effect until any version edited or added.'),
        ),
        migrations.AlterField(
            model_name='version',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='version',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
