# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0014_auto_20170326_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='advanced_mode',
            field=models.BooleanField(default=False, help_text='Check it to generate awesome depiction page for each version.', verbose_name='Auto Depiction'),
        ),
    ]
