# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0014_auto_20170128_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='architecture',
            field=models.CharField(default='', help_text='The architecture specifies which type of hardware this package was compiled for.  Common architectures are amd64, armel, i386, powerpc, etc.  Note that the all value is meant for packages that are architecture independent.  Some examples of this are shell and Perl scripts, and documentation.', max_length=255, verbose_name='Architecture'),
        ),
    ]
