# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0015_auto_20170327_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='redirect_resources',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Moved'), (2, 'Accel')], default=0, help_text='None - Read resources and return, without partical support, not recommended.<br />Moved - Return 301/302 responses and redirect to the real resource urls.<br />Accel - Redirect resource requests to WEB servers without changing urls.', verbose_name='Redirect Methods'),
        ),
    ]
