# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0016_auto_20170128_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='active_release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WEIPDCRM.Release'),
        ),
    ]
