# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0017_setting_version_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='comments',
        ),
        migrations.AddField(
            model_name='setting',
            name='enable_comments',
            field=models.BooleanField(default=False, help_text='Enable comments module', verbose_name='Comments'),
        ),
    ]
