# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0018_auto_20170128_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='releases',
            field=models.ManyToManyField(blank=True, to='WEIPDCRM.Release'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='active_release',
            field=models.ForeignKey(blank=True, help_text='Each repository should have an active release, otherwise it will not be recognized by any advanced package tools.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WEIPDCRM.Release'),
        ),
    ]
