# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0020_auto_20170415_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='favicon',
            field=models.FileField(blank=True, help_text='Choose an Icon (*.png) to upload', max_length=255, null=True, upload_to='favicon', verbose_name='Favicon'),
        ),
    ]
