# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0020_auto_20170128_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='packages_validation',
            field=models.IntegerField(choices=[(0, 'No validation'), (1, 'MD5Sum'), (2, 'MD5Sum & SHA1'), (3, 'MD5Sum & SHA1 & SHA256 (Recommended)'), (4, 'MD5Sum & SHA1 & SHA256 & SHA512')], default=1, help_text='It will not take effect until any version edited or added.', verbose_name='Packages Validation'),
        ),
        migrations.AlterField(
            model_name='version',
            name='sha512',
            field=models.CharField(default='', max_length=128, verbose_name='SHA512'),
        ),
    ]
