# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0021_auto_20170130_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='releases',
        ),
        migrations.RemoveField(
            model_name='package',
            name='section',
        ),
        migrations.AddField(
            model_name='version',
            name='architecture',
            field=models.CharField(default='', help_text='This describes what system a package is designed for, as .deb files are used on everything from the iPhone to your desktop computer. The correct value for iPhoneOS 1.0.x/1.1.x is "darwin-arm". If you are deploying to iPhoneOS 1.2/2.x you should use "iphoneos-arm".', max_length=255, verbose_name='Architecture'),
        ),
        migrations.AddField(
            model_name='version',
            name='author_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Author Email'),
        ),
        migrations.AddField(
            model_name='version',
            name='author_name',
            field=models.CharField(blank=True, help_text='In contrast, the person who wrote the original software is called the "author". This name will be shown underneath the name of the package on the details screen. The field is in the same format as "Maintainer".', max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='version',
            name='depiction',
            field=models.URLField(blank=True, default='', help_text='Pretty much the entire interface of Cydia is a webpage, which makes adding features or new functionality remotely very easy. One thing you might want is to be able to display custom links or screenshots with special formatting... just plain something special (even an advertisement) on your package page. This is done with a "depiction", which is a URL that is loaded into an iframe, replacing the Description: and Homepage: links that are normally presnt. For a good example see WinterBoard\'s package details page in Cydia. For many packagers this has simply become their More Information page, which is only used for backwards compatibility. It does not need to be the same, however. You also may consider not having a Homepage: field at all if you include Depiction:.', null=True, verbose_name='Depiction'),
        ),
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, default='', help_text="This field is a little more complicated than the others, as it may use multiple lines. The first line (after the colon) should contain a short description to be displayed on the package lists underneath the name of the package. Optionally, one can choose to replace that description with an arbitrarily long one that will be displayed on the package details screen. Technically the format for this field is quite complicated, but most of that complexity is currently ignored by Cydia: instead Cydia allows you to place arbitrarily awesome HTML in this field. Each line of this extended description must begin with a space. I highly disrecommend using this for HTML, however: you should instead use Depiction: for the description in Cydia and use extended descriptions (which will then be ignored by Cydia) for compatibility with command-line clients. I would normally leave this mess undocumented, but this is so different from APT/dpkg that I feel the need to do a full explanation here. Arguably, at some future point, I should redo this field in Cydia to be parsed correctly, so another way of looking at this is that extended descriptions shouldn't be used with Cydia at all.", null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='version',
            name='homepage',
            field=models.URLField(blank=True, default='', help_text='Often, there is more information that a packager wants to provide about a package than can be listed in the description of the package. Cydia supports a "More Info" field on the details screen that shunts users off to a website of the packager\'s choice.', null=True, verbose_name='Homepage'),
        ),
        migrations.AddField(
            model_name='version',
            name='icon',
            field=models.ImageField(blank=True, help_text='Choose an Icon (*.png) to upload', null=True, upload_to='package-icons', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='version',
            name='maintainer_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Maintainer Email'),
        ),
        migrations.AddField(
            model_name='version',
            name='maintainer_name',
            field=models.CharField(blank=True, help_text='It is typically the person who created the package, as opposed to the author of the software that was packaged.', max_length=255, null=True, verbose_name='Maintainer'),
        ),
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.CharField(default='Untitled Package', help_text='When the package is shown in Cydia\'s lists, it is convenient to have a prettier name. This field allows you to override this display with an arbitrary string. This field may change often, whereas the "Package" field is fixed for the lifetime of the package.', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='version',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Under the "Install" tab in Cydia, packages are listed by "Section". If you would like to encode a space into your section name, use an underscore (Cydia will automatically convert these).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WEIPDCRM.Section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='version',
            name='sponsor_name',
            field=models.CharField(blank=True, help_text='Finally, there might be someone who is simply providing the influence or the cash to make the package happen. This person should be listed here in the form of "Maintainer" except using a resource URI instead of an e-mail address.', max_length=255, null=True, verbose_name='Sponsor'),
        ),
        migrations.AddField(
            model_name='version',
            name='sponsor_site',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Sponsor Site'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='This is a general field that gives the package a category based on the software that it installs. You will not be able to edit its name after assigning any package under it.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='downgrade_support',
            field=models.BooleanField(default=True, help_text='Allow multiple versions to exist in the latest package list.', verbose_name='Downgrade Support'),
        ),
        migrations.AlterField(
            model_name='version',
            name='package',
            field=models.CharField(help_text='This is the "identifier" of the package. This should be, entirely in lower case, a reversed hostname (much like a "bundleIdentifier" in Apple\'s Info.plist files). If you are also choosing to host an AppTapp Installer repository to support legacy clients, you are strongly encouraged to make this name match the AppTapp bundle identifier (except all in lower case).', max_length=255, unique=True, verbose_name='Package'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
