# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0021_auto_20170415_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'managed': False, 'verbose_name': '\u8f6f\u4ef6\u5305', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterField(
            model_name='osversion',
            name='descriptor',
            field=models.CharField(help_text='Example: 10.2', max_length=255, verbose_name='\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, help_text='On the package source screen a short description is listed of the repository. This description may eventually work similarly to that of a package (with a long/short variety and the aforementioned encoding), but for right now only the shorter description is displayed directly on the list.', verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='release',
            name='support',
            field=models.URLField(blank=True, help_text='Official site to provide support.', max_length=255, null=True, verbose_name='\u652f\u6301'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(default='0.0.1-1', help_text='This is an arbitrary version number that nothing actually parses. I am going to look into seeing how required it is.', max_length=255, verbose_name='\u7248\u672c'),
        ),
    ]
