# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0022_auto_20170216_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='priority',
            field=models.CharField(blank=True, choices=[('required', 'Required'), ('standard', 'Standard'), ('optional', 'Optional'), ('extra', 'Extra')], default='', help_text='Sets the importance of this package in relation to the system as a whole.  Common priorities are required, standard, optional, extra, etc.', max_length=255, null=True, verbose_name='Priority'),
        ),
    ]
