# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0022_auto_20170812_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='advertisement',
            field=models.TextField(blank=True, default='', help_text='HTML Displayed on the frontend widget and the auto depiction page (mobile).', null=True, verbose_name='Advertisement'),
        ),
        migrations.AddField(
            model_name='setting',
            name='external_statistics',
            field=models.TextField(blank=True, default='', help_text='Invisible statistic code.', null=True, verbose_name='External Statistics'),
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Facebook Name'),
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Display Facebook link on the package info page.', max_length=255, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='setting',
            name='internal_statistics',
            field=models.TextField(blank=True, default='', help_text='Statistics code of view information at statistics page.', null=True, verbose_name='Internal Statistics'),
        ),
        migrations.AddField(
            model_name='setting',
            name='notice',
            field=models.TextField(blank=True, default='', help_text='HTML Displayed on the frontend widget and the auto depiction page (mobile).', null=True, verbose_name='Notice'),
        ),
        migrations.AddField(
            model_name='setting',
            name='paypal_url',
            field=models.URLField(blank=True, help_text='Display "Donate via Paypal" link on the package info page.', max_length=255, null=True, verbose_name='Paypal URL'),
        ),
        migrations.AddField(
            model_name='setting',
            name='twitter_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Twitter Name'),
        ),
        migrations.AddField(
            model_name='setting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Display Twitter link on the package info page.', max_length=255, null=True, verbose_name='Twitter URL'),
        ),
    ]
