# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0023_auto_20170813_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='telegram_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram Name'),
        ),
        migrations.AddField(
            model_name='setting',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='Display Telegram link on the package info page.', max_length=255, null=True, verbose_name='Telegram URL'),
        ),
    ]
