# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 13:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0024_auto_20170814_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'managed': False, 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AddField(
            model_name='setting',
            name='redirect_prefix',
            field=models.CharField(blank=True, help_text='Changing scheme and host of the url in package downloading requests, which is useful for load balancing or CDN speedup.<br />Example: https://cdn.82flex.com', max_length=128, null=True, validators=[django.core.validators.URLValidator], verbose_name='Redirect Prefix'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='descriptor',
            field=models.CharField(help_text='Example: 10.2', max_length=255, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, help_text='On the package source screen a short description is listed of the repository. This description may eventually work similarly to that of a package (with a long/short variety and the aforementioned encoding), but for right now only the shorter description is displayed directly on the list.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='release',
            name='support',
            field=models.URLField(blank=True, help_text='Official site to provide support.', max_length=255, null=True, verbose_name='Support'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(default='0.0.1-1', help_text='This is an arbitrary version number that nothing actually parses. I am going to look into seeing how required it is.', max_length=255, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='alipay_url',
            field=models.URLField(blank=True, help_text='Display "Donate via Alipay" link on the package info page.', max_length=255, null=True, validators=[django.core.validators.URLValidator], verbose_name='Alipay URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Display Facebook link on the package info page.', max_length=255, null=True, validators=[django.core.validators.URLValidator], verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='paypal_url',
            field=models.URLField(blank=True, help_text='Display "Donate via Paypal" link on the package info page.', max_length=255, null=True, validators=[django.core.validators.URLValidator], verbose_name='Paypal URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='qq_group_url',
            field=models.URLField(blank=True, help_text='Display QQ group link on the package info page.', max_length=255, null=True, validators=[django.core.validators.URLValidator], verbose_name='QQ Group URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='Display Telegram link on the package info page.', max_length=255, null=True, validators=[django.core.validators.URLValidator], verbose_name='Telegram URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Display Twitter link on the package info page.', max_length=255, null=True, validators=[django.core.validators.URLValidator], verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weibo_url',
            field=models.URLField(blank=True, help_text='Display Weibo link on the package info page.', max_length=255, null=True, validators=[django.core.validators.URLValidator], verbose_name='Weibo URL'),
        ),
    ]
