# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0024_auto_20170216_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='architecture',
            field=models.CharField(blank=True, default='', help_text='This describes what system a package is designed for, as .deb files are used on everything from the iPhone to your desktop computer. The correct value for iPhoneOS 1.0.x/1.1.x is "darwin-arm". If you are deploying to iPhoneOS 1.2/2.x you should use "iphoneos-arm".', max_length=255, null=True, verbose_name='Architecture'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(blank=True, default='Untitled Package', help_text='When the package is shown in Cydia\'s lists, it is convenient to have a prettier name. This field allows you to override this display with an arbitrary string. This field may change often, whereas the "Package" field is fixed for the lifetime of the package.', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
