# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0025_auto_20170216_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='control_field',
        ),
        migrations.AlterField(
            model_name='version',
            name='architecture',
            field=models.CharField(blank=True, default='', help_text='This describes what system a package is designed for, as .deb files are used on everything from the iPhone to your desktop computer. The correct value for iPhoneOS 1.0.x/1.1.x is "darwin-arm". If you are deploying to iPhoneOS 1.2/2.x you should use "iphoneos-arm".', max_length=255, verbose_name='Architecture'),
        ),
        migrations.AlterField(
            model_name='version',
            name='author_email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='Author Email'),
        ),
        migrations.AlterField(
            model_name='version',
            name='author_name',
            field=models.CharField(blank=True, default='', help_text='In contrast, the person who wrote the original software is called the "author". This name will be shown underneath the name of the package on the details screen. The field is in the same format as "Maintainer".', max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='version',
            name='breaks',
            field=models.TextField(blank=True, default='', help_text='Lists packages that this one breaks, for example by exposing bugs when the named packages rely on this one. The package maintenance software will not allow broken packages to be configured; generally the resolution is to upgrade the packages named in a Breaks field.', verbose_name='Breaks'),
        ),
        migrations.AlterField(
            model_name='version',
            name='bugs',
            field=models.URLField(blank=True, default='', help_text='The url of the bug tracking system for this package. The current used format is bts-type://bts-address, like debbugs://bugs.debian.org.', verbose_name='Bugs'),
        ),
        migrations.AlterField(
            model_name='version',
            name='build_essential',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', help_text='This field is usually only needed when the answer is yes, and is commonly injected by the archive software.  It denotes a package that is required when building other packages.', max_length=255, verbose_name='Build Essential'),
        ),
        migrations.AlterField(
            model_name='version',
            name='built_for_profiles',
            field=models.TextField(blank=True, default='', help_text='This field specifies a whitespace separated list of build profiles that this binary packages was built with.', verbose_name='Built-For-Profiles'),
        ),
        migrations.AlterField(
            model_name='version',
            name='built_using',
            field=models.TextField(blank=True, default='', help_text="This field lists extra source packages that were used during the build of this binary package.  This is an indication to the archive maintenance software that these extra source packages must be kept whilst this binary package is maintained. This field must be a list of source package names with strict '=' version relationships.  Note that the archive maintenance software is likely to refuse to accept an upload which declares a Built-Using relationship which cannot be satisfied within the archive.", verbose_name='Built-Using'),
        ),
        migrations.AlterField(
            model_name='version',
            name='conflicts',
            field=models.TextField(blank=True, default='', help_text='Lists packages that conflict with this one, for example by containing files with the same names. The package maintenance software will not allow conflicting packages to be installed at the same time. Two conflicting packages should each include a Conflicts line mentioning the other.', verbose_name='Conflicts'),
        ),
        migrations.AlterField(
            model_name='version',
            name='depends',
            field=models.TextField(blank=True, default='', help_text="List of packages that are required for this package to provide a non-trivial amount of functionality. The package maintenance software will not allow a package to be installed if the packages listed in its Depends field aren't installed (at least not without using the force options).  In an installation, the postinst scripts of packages listed in Depends fields are run before those of the packages which depend on them. On the opposite, in a removal, the prerm script of a package is run before those of the packages listed in its Depends field.", verbose_name='Depends'),
        ),
        migrations.AlterField(
            model_name='version',
            name='depiction',
            field=models.URLField(blank=True, default='', help_text='Pretty much the entire interface of Cydia is a webpage, which makes adding features or new functionality remotely very easy. One thing you might want is to be able to display custom links or screenshots with special formatting... just plain something special (even an advertisement) on your package page. This is done with a "depiction", which is a URL that is loaded into an iframe, replacing the Description: and Homepage: links that are normally presnt. For a good example see WinterBoard\'s package details page in Cydia. For many packagers this has simply become their More Information page, which is only used for backwards compatibility. It does not need to be the same, however. You also may consider not having a Homepage: field at all if you include Depiction:.', verbose_name='Depiction'),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, default='', help_text="This field is a little more complicated than the others, as it may use multiple lines. The first line (after the colon) should contain a short description to be displayed on the package lists underneath the name of the package. Optionally, one can choose to replace that description with an arbitrarily long one that will be displayed on the package details screen. Technically the format for this field is quite complicated, but most of that complexity is currently ignored by Cydia: instead Cydia allows you to place arbitrarily awesome HTML in this field. Each line of this extended description must begin with a space. I highly disrecommend using this for HTML, however: you should instead use Depiction: for the description in Cydia and use extended descriptions (which will then be ignored by Cydia) for compatibility with command-line clients. I would normally leave this mess undocumented, but this is so different from APT/dpkg that I feel the need to do a full explanation here. Arguably, at some future point, I should redo this field in Cydia to be parsed correctly, so another way of looking at this is that extended descriptions shouldn't be used with Cydia at all.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='version',
            name='device_compatibility',
            field=models.ManyToManyField(blank=True, null=True, to='WEIPDCRM.DeviceType', verbose_name='Device Compatibility'),
        ),
        migrations.AlterField(
            model_name='version',
            name='essential',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', help_text='This field is usually only needed when the answer is yes. It denotes a package that is required for proper operation of the system. Dpkg or any other installation tool will not allow an Essential package to be removed (at least not without using one of the force options).', max_length=255, verbose_name='Essential'),
        ),
        migrations.AlterField(
            model_name='version',
            name='homepage',
            field=models.URLField(blank=True, default='', help_text='Often, there is more information that a packager wants to provide about a package than can be listed in the description of the package. Cydia supports a "More Info" field on the details screen that shunts users off to a website of the packager\'s choice.', verbose_name='Homepage'),
        ),
        migrations.AlterField(
            model_name='version',
            name='icon',
            field=models.ImageField(blank=True, default='', help_text='Choose an Icon (*.png) to upload', upload_to='package-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='version',
            name='installer_menu_item',
            field=models.TextField(blank=True, default='', help_text='These fields are used by the debian-installer and are usually not needed. See /usr/share/doc/debian-installer/devel/modules.txt from the debian-installer package for more details about them.', verbose_name='Installer-Menu-Item'),
        ),
        migrations.AlterField(
            model_name='version',
            name='kernel_version',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kernel-Version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='maintainer_email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='Maintainer Email'),
        ),
        migrations.AlterField(
            model_name='version',
            name='maintainer_name',
            field=models.CharField(blank=True, default='', help_text='It is typically the person who created the package, as opposed to the author of the software that was packaged.', max_length=255, verbose_name='Maintainer'),
        ),
        migrations.AlterField(
            model_name='version',
            name='multi_arch',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('same', 'Same'), ('foreign', 'Foreign'), ('allowed', 'Allowed')], default='', help_text='This field is used to indicate how this package should behave on a multi-arch installations.<br /><ul><li>no - This value is the default when the field is omitted, in which case adding the field with an explicit no value is generally not needed.</li><li>same - This package is co-installable with itself, but it must not be used to satisfy the dependency of any package of a different architecture from itself.</li><li>foreign - This package is not co-installable with itself, but should be allowed to satisfy a non-arch-qualified dependency of a package of a different arch from itself (if a dependency has an explicit arch-qualifier then the value foreign is ignored).</li><li>allowed - This allows reverse-dependencies to indicate in their Depends field that they accept this package from a foreign architecture by qualifying the package name with :any, but has no effect otherwise.</li></ul>', max_length=255, verbose_name='Multi-Arch'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(blank=True, default='Untitled Package', help_text='When the package is shown in Cydia\'s lists, it is convenient to have a prettier name. This field allows you to override this display with an arbitrary string. This field may change often, whereas the "Package" field is fixed for the lifetime of the package.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='version',
            name='origin',
            field=models.CharField(blank=True, default='', help_text='The name of the distribution this package is originating from.', max_length=255, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='version',
            name='os_compatibility',
            field=models.ManyToManyField(blank=True, null=True, to='WEIPDCRM.OSVersion', verbose_name='OS Compatibility'),
        ),
        migrations.AlterField(
            model_name='version',
            name='pre_depends',
            field=models.TextField(blank=True, default='', help_text='List of packages that must be installed and configured before this one can be installed. This is usually used in the case where this package requires another package for running its preinst script.', verbose_name='Pre-Depends'),
        ),
        migrations.AlterField(
            model_name='version',
            name='priority',
            field=models.CharField(blank=True, choices=[('required', 'Required'), ('standard', 'Standard'), ('optional', 'Optional'), ('extra', 'Extra')], default='', help_text='Sets the importance of this package in relation to the system as a whole.  Common priorities are required, standard, optional, extra, etc.', max_length=255, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='version',
            name='provides',
            field=models.TextField(blank=True, default='', help_text='This is a list of virtual packages that this one provides. Usually this is used in the case of several packages all providing the same service. For example, sendmail and exim can serve as a mail server, so they provide a common package ("mail-transport-agent") on which other packages can depend. This will allow sendmail or exim to serve as a valid option to satisfy the dependency.  This prevents the packages that depend on a mail server from having to know the package names for all of them, and using \'|\' to separate the list.', verbose_name='Provides'),
        ),
        migrations.AlterField(
            model_name='version',
            name='recommends',
            field=models.TextField(blank=True, default='', help_text='Lists packages that would be found together with this one in all but unusual installations. The package maintenance software will warn the user if they install a package without those listed in its Recommends field.', verbose_name='Recommends'),
        ),
        migrations.AlterField(
            model_name='version',
            name='replaces',
            field=models.TextField(blank=True, default='', help_text='List of packages files from which this one replaces. This is used for allowing this package to overwrite the files of another package and is usually used with the Conflicts field to force removal of the other package, if this one also has the same files as the conflicted package.', verbose_name='Conflicts'),
        ),
        migrations.AlterField(
            model_name='version',
            name='section',
            field=models.ForeignKey(blank=True, default='', help_text='Under the "Install" tab in Cydia, packages are listed by "Section". If you would like to encode a space into your section name, use an underscore (Cydia will automatically convert these).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WEIPDCRM.Section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='version',
            name='source',
            field=models.CharField(blank=True, default='', help_text='The name of the source package that this binary package came from, if it is different than the name of the package itself. If the source version differs from the binary version, then the source-name will be followed by a source-version in parenthesis.  This can happen for example on a binary-only non-maintainer upload, or when setting a different binary version via \xabdpkg-gencontrol -v\xbb.', max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='version',
            name='sponsor_name',
            field=models.CharField(blank=True, default='', help_text='Finally, there might be someone who is simply providing the influence or the cash to make the package happen. This person should be listed here in the form of "Maintainer" except using a resource URI instead of an e-mail address.', max_length=255, verbose_name='Sponsor'),
        ),
        migrations.AlterField(
            model_name='version',
            name='sponsor_site',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Sponsor Site'),
        ),
        migrations.AlterField(
            model_name='version',
            name='subarchitecture',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Subarchitecture'),
        ),
        migrations.AlterField(
            model_name='version',
            name='suggests',
            field=models.TextField(blank=True, default='', help_text='Lists packages that are related to this one and can perhaps enhance its usefulness, but without which installing this package is perfectly reasonable.', verbose_name='Suggests'),
        ),
        migrations.AlterField(
            model_name='version',
            name='tag',
            field=models.TextField(blank=True, default='', help_text='List of tags describing the qualities of the package. The description and list of supported tags can be found in the debtags package.', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='version',
            name='update_logs',
            field=models.TextField(blank=True, default='', verbose_name='Update Logs'),
        ),
    ]
