# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-05 15:30
from __future__ import unicode_literals

import WEIPDCRM.models.setting
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0026_package_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ('-created_at',), 'verbose_name': '\u6784\u5efa', 'verbose_name_plural': '\u6784\u5efa'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': '\u8bbe\u5907\u7c7b\u578b', 'verbose_name_plural': '\u8bbe\u5907\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='osversion',
            options={'verbose_name': 'iOS \u7248\u672c', 'verbose_name_plural': 'iOS \u7248\u672c'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'managed': False, 'verbose_name': '\u8f6f\u4ef6\u5305', 'verbose_name_plural': '\u8f6f\u4ef6\u5305'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'verbose_name': '\u5143\u6570\u636e', 'verbose_name_plural': '\u5143\u6570\u636e'},
        ),
        migrations.AlterField(
            model_name='build',
            name='active_release',
            field=models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='WEIPDCRM.Release', verbose_name='\u6d3b\u8dc3\u5143\u6570\u636e'),
        ),
        migrations.AlterField(
            model_name='build',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='build',
            name='details',
            field=models.TextField(blank=True, default='', help_text='\u8bf7\u63cf\u8ff0\u91cd\u65b0\u6784\u5efa\u8be5\u5b58\u50a8\u5e93\u7684\u7406\u7531.', null=True, verbose_name='\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='build',
            name='job_id',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='\u4efb\u52a1 ID'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='descriptor',
            field=models.CharField(help_text='\u4f8b: iPhone 7 Plus', max_length=255, verbose_name='\u63cf\u8ff0\u7b26'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='icon',
            field=models.FileField(blank=True, help_text='\u8bf7\u9009\u62e9\u5e76\u4e0a\u4f20\u4e00\u4e2a\u56fe\u6807 (*.png)', max_length=255, null=True, upload_to='device-icons', verbose_name='\u56fe\u6807'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='platform',
            field=models.CharField(blank=True, help_text='\u4f8b: A1661/A1784/A1785', max_length=255, verbose_name='\u5e73\u53f0'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='subtype',
            field=models.CharField(help_text='\u4f8b: iPhone9,2', max_length=255, verbose_name='\u5b50\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='build',
            field=models.CharField(help_text='\u4f8b: 14C92/11A466', max_length=255, verbose_name='\u6784\u5efa'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='descriptor',
            field=models.CharField(help_text='\u4f8b: 10.2', max_length=255, verbose_name='\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='icon',
            field=models.FileField(blank=True, help_text='\u8bf7\u9009\u62e9\u5e76\u4e0a\u4f20\u4e00\u4e2a\u56fe\u6807 (*.png)', max_length=255, null=True, upload_to='os-icons', verbose_name='\u56fe\u6807'),
        ),
        migrations.AlterField(
            model_name='release',
            name='architectures',
            field=models.CharField(blank=True, default='iphoneos-arm', help_text='\u53ea\u9700\u8981\u8bbe\u7f6e\u4e3a "iphoneos-arm" \u5373\u53ef, \u4ee3\u8868 iOS \u5e73\u53f0. ', max_length=255, verbose_name='\u67b6\u6784'),
        ),
        migrations.AlterField(
            model_name='release',
            name='codename',
            field=models.CharField(blank=True, default='', help_text='\u5728 "\u81ea\u52a8" \u5b58\u50a8\u5e93\u4e2d, \u60a8\u53ef\u4ee5\u4e3a\u4e0d\u540c\u7684\u76ee\u6807\u7cfb\u7edf\u5b58\u50a8\u591a\u4e2a\u53d1\u884c\u7248\u672c. \u4f8b\u5982: "apt.saurik.com" \u7684\u4e3b\u5b58\u50a8\u5e93\u5305\u542b\u684c\u9762\u7248 Debian Etch \u7cfb\u7edf\u4ee5\u53ca iPhone \u5e73\u53f0\u7684\u5185\u5bb9. \u8fd9\u4e2a\u4ee3\u53f7\u63cf\u8ff0\u4e86\u6211\u4eec\u76ee\u524d\u6b63\u5728\u5bfb\u627e\u4ec0\u4e48\u53d1\u884c\u7248. ', max_length=255, verbose_name='\u4ee3\u53f7'),
        ),
        migrations.AlterField(
            model_name='release',
            name='components',
            field=models.CharField(blank=True, default='main', help_text='\u53ea\u9700\u8981\u8bbe\u7f6e\u4e3a "main" \u5373\u53ef. ', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='\u7ec4\u4ef6'),
        ),
        migrations.AlterField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u4e8e'),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, help_text='\u5728\u8f6f\u4ef6\u5305\u6e90\u4fe1\u606f\u90e8\u5206\u4e0a, \u4f1a\u5217\u51fa\u5b58\u50a8\u5e93\u7684\u7b80\u77ed\u8bf4\u660e. ', verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='release',
            name='email',
            field=models.EmailField(blank=True, help_text='\u7ef4\u62a4\u8005\u7528\u4e8e\u63d0\u4f9b\u6280\u672f\u652f\u6301\u7684\u7535\u5b50\u90ae\u7bb1. ', max_length=255, null=True, verbose_name='\u7535\u5b50\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='release',
            name='icon',
            field=models.FileField(blank=True, help_text='\u8bf7\u9009\u62e9\u5e76\u4e0a\u4f20\u4e00\u4e2a\u56fe\u6807 (*.png)', max_length=255, null=True, upload_to='repository-icons', verbose_name='\u5b58\u50a8\u5e93\u56fe\u6807'),
        ),
        migrations.AlterField(
            model_name='release',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='\u4ee5\u82f1\u6587\u534a\u89d2\u9017\u53f7\u5206\u9694. ', max_length=255, verbose_name='\u5173\u952e\u8bcd'),
        ),
        migrations.AlterField(
            model_name='release',
            name='label',
            field=models.CharField(default='', help_text='\u5728\u8f6f\u4ef6\u5305\u5217\u8868\u754c\u9762\u4e0a, Cydia \u4f1a\u663e\u793a\u8be5\u8f6f\u4ef6\u5305\u6765\u81ea\u4e8e\u54ea\u4e2a\u5b58\u50a8\u5e93\u548c\u5206\u7c7b. \u4f46\u662f, \u8fd9\u4e2a\u4f4d\u7f6e\u6ca1\u6709\u592a\u591a\u7a7a\u95f4, \u56e0\u6b64\u8be5\u5b57\u6bb5\u5e94\u5305\u542b\u53ef\u7528\u4f5c\u6807\u8bb0\u7684\u5b58\u50a8\u5e93\u540d\u79f0\u7684\u8f83\u77ed\u6216\u8f83\u7b80\u5355\u7684\u7248\u672c. ', max_length=255, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='release',
            name='origin',
            field=models.CharField(default='', help_text='Cydia \u5c06\u8be5\u5b57\u6bb5\u663e\u793a\u4e8e\u6e90\u4ee3\u7801\u7f16\u8f91\u5668 (\u4ee5\u53ca\u5176\u4ed6\u5730\u65b9) \u4e2d. \u8fd9\u5e94\u8be5\u5b58\u50a8\u5e93\u7684\u4e00\u4e2a\u8f83\u957f\u7684, \u4f46\u4e0d\u662f\u975e\u5e38\u957f\u7684\u63cf\u8ff0\u6027\u540d\u79f0. ', max_length=255, verbose_name='\u521d\u59cb'),
        ),
        migrations.AlterField(
            model_name='release',
            name='suite',
            field=models.CharField(blank=True, default='stable', help_text='\u53ea\u9700\u8981\u8bbe\u7f6e\u4e3a "stable" \u5373\u53ef, \u5177\u4f53\u4f5c\u7528\u4e0d\u660e\u786e. ', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='\u5957\u88c5'),
        ),
        migrations.AlterField(
            model_name='release',
            name='support',
            field=models.URLField(blank=True, help_text='\u7528\u4e8e\u63d0\u4f9b\u6280\u672f\u652f\u6301\u7684\u5b98\u65b9\u7f51\u7ad9. ', max_length=255, null=True, verbose_name='\u652f\u6301'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(default='0.0.1-1', help_text='\u8fd9\u662f\u4e00\u4e2a\u53ef\u968f\u610f\u586b\u5199\u7684\u7248\u672c\u53f7\u6570\u503c. ', max_length=255, verbose_name='\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='redirect_prefix',
            field=models.CharField(blank=True, help_text='Changing scheme and host of the url in package downloading requests, which is useful for load balancing or CDN speedup.<br />Example: https://cdn.82flex.com/', max_length=128, null=True, validators=[django.core.validators.URLValidator, WEIPDCRM.models.setting.validate_slash], verbose_name='Redirect Prefix'),
        ),
    ]
