# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0026_auto_20170216_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='device_compatibility',
            field=models.ManyToManyField(blank=True, to='WEIPDCRM.DeviceType', verbose_name='Device Compatibility'),
        ),
        migrations.AlterField(
            model_name='version',
            name='os_compatibility',
            field=models.ManyToManyField(blank=True, to='WEIPDCRM.OSVersion', verbose_name='OS Compatibility'),
        ),
    ]
