# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 14:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('WEIPDCRM', '0027_auto_20180405_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ('-created_at',), 'verbose_name': 'Build', 'verbose_name_plural': 'Builds'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Types'},
        ),
        migrations.AlterModelOptions(
            name='osversion',
            options={'verbose_name': 'iOS Version', 'verbose_name_plural': 'iOS Versions'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'managed': False, 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'verbose_name': 'Release', 'verbose_name_plural': 'Releases'},
        ),
        migrations.AddField(
            model_name='version',
            name='gallery',
            field=models.ForeignKey(blank=True, default=None, help_text='You can manage screenshots in Photologue.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery', verbose_name='Gallery'),
        ),
        migrations.AlterField(
            model_name='build',
            name='active_release',
            field=models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='WEIPDCRM.Release', verbose_name='Active Release'),
        ),
        migrations.AlterField(
            model_name='build',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='build',
            name='details',
            field=models.TextField(blank=True, default='', help_text='Tell others what did you do this time before you rebuild the repository.', null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='build',
            name='job_id',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Job ID'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='descriptor',
            field=models.CharField(help_text='Example: iPhone 7 Plus', max_length=255, verbose_name='Descriptor'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='icon',
            field=models.FileField(blank=True, help_text='Choose an Icon (*.png) to upload', max_length=255, null=True, upload_to='device-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='platform',
            field=models.CharField(blank=True, help_text='Example: A1661/A1784/A1785', max_length=255, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='subtype',
            field=models.CharField(help_text='Example: iPhone9,2', max_length=255, verbose_name='Subtype'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='build',
            field=models.CharField(help_text='Example: 14C92/11A466', max_length=255, verbose_name='Build'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='descriptor',
            field=models.CharField(help_text='Example: 10.2', max_length=255, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='osversion',
            name='icon',
            field=models.FileField(blank=True, help_text='Choose an Icon (*.png) to upload', max_length=255, null=True, upload_to='os-icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='release',
            name='architectures',
            field=models.CharField(blank=True, default='iphoneos-arm', help_text='To verify a repository is for the specific device you are working with APT looks in the release file for this list. You must specify all of the architectures that appear in your Packages file here. Again, we use darwin-arm for 1.1.x and iphoneos-arm for 2.x.', max_length=255, verbose_name='Architectures'),
        ),
        migrations.AlterField(
            model_name='release',
            name='codename',
            field=models.CharField(blank=True, default='', help_text='In an "automatic" repository you might store multiple distributions of software for different target systems. For example: apt.saurik.com\'s main repository houses content both for desktop Debian Etch systems as well as the iPhone. This codename then describes what distribution we are currently looking for.', max_length=255, verbose_name='Codename'),
        ),
        migrations.AlterField(
            model_name='release',
            name='components',
            field=models.CharField(blank=True, default='main', help_text='Just set this to "main". This field might not be required, but who really knows? I, for certain, do not.', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Components'),
        ),
        migrations.AlterField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, help_text='On the package source screen a short description is listed of the repository. This description may eventually work similarly to that of a package (with a long/short variety and the aforementioned encoding), but for right now only the shorter description is displayed directly on the list.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='release',
            name='email',
            field=models.EmailField(blank=True, help_text="Maintainer's E-mail to provide support.", max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='release',
            name='icon',
            field=models.FileField(blank=True, help_text='Choose an Icon (*.png) to upload', max_length=255, null=True, upload_to='repository-icons', verbose_name='Repository Icon'),
        ),
        migrations.AlterField(
            model_name='release',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='Separated by commas.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='release',
            name='label',
            field=models.CharField(default='', help_text="On the package list screens, Cydia shows what repository and section packages came from. This location doesn't have much room, though, so this field should contain a shorter/simpler version of the name of the repository that can be used as a tag.", max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='release',
            name='origin',
            field=models.CharField(default='', help_text='This is used by Cydia as the name of the repository as shown in the source editor (and elsewhere). This should be a longer, but not insanely long, description of the repository.', max_length=255, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='release',
            name='suite',
            field=models.CharField(blank=True, default='stable', help_text='Just set this to "stable". This field might not be required, but who really knows? I, for certain, do not.', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Suite'),
        ),
        migrations.AlterField(
            model_name='release',
            name='support',
            field=models.URLField(blank=True, help_text='Official site to provide support.', max_length=255, null=True, verbose_name='Support'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(default='0.0.1-1', help_text='This is an arbitrary version number that nothing actually parses. I am going to look into seeing how required it is.', max_length=255, verbose_name='Version'),
        ),
    ]
