# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0028_auto_20170216_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='replaces',
            field=models.TextField(blank=True, default='', help_text='List of packages files from which this one replaces. This is used for allowing this package to overwrite the files of another package and is usually used with the Conflicts field to force removal of the other package, if this one also has the same files as the conflicted package.', null=True, verbose_name='Conflicts'),
        ),
    ]
