# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 09:15
from __future__ import unicode_literals

import WEIPDCRM.models.setting
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0028_auto_20190722_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='rest_api',
            field=models.BooleanField(default=True, help_text='Upload packages using HTTP, manage your repositories, snapshots and comments etc.', validators=[WEIPDCRM.models.setting.validate_rest_api], verbose_name='Enable Rest API'),
        ),
    ]
