# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0029_auto_20170216_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='name',
            new_name='display_name',
        ),
    ]
