# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0030_build_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='details',
            field=models.TextField(blank=True, default='Fast Build', help_text='Tell others what did you do this time before you rebuild the repository.', null=True, verbose_name='Details'),
        ),
    ]
