# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-17 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0031_auto_20170216_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='atomic_storage',
            field=models.BooleanField(default=False, help_text='Generate a new copy of package after editing control columns.', verbose_name='Atomic Storage'),
        ),
        migrations.AlterField(
            model_name='version',
            name='build_essential',
            field=models.CharField(blank=True, choices=[(None, '-'), ('yes', 'Yes'), ('no', 'No')], default='', help_text='This field is usually only needed when the answer is yes, and is commonly injected by the archive software.  It denotes a package that is required when building other packages.', max_length=255, null=True, verbose_name='Build-Essential'),
        ),
        migrations.AlterField(
            model_name='version',
            name='depiction',
            field=models.URLField(blank=True, default='', help_text='This is a URL that is loaded into an iframe, replacing the Description: and Homepage: .', null=True, verbose_name='Depiction'),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The first line (after the colon) should contain a short description to be displayed on the package lists underneath the name of the package. Optionally, one can choose to replace that description with an arbitrarily long one that will be displayed on the package details screen.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='version',
            name='essential',
            field=models.CharField(blank=True, choices=[(None, '-'), ('yes', 'Yes'), ('no', 'No')], default='', help_text='This field is usually only needed when the answer is yes. It denotes a package that is required for proper operation of the system. Dpkg or any other installation tool will not allow an Essential package to be removed (at least not without using one of the force options).', max_length=255, null=True, verbose_name='Essential'),
        ),
        migrations.AlterField(
            model_name='version',
            name='homepage',
            field=models.URLField(blank=True, default='', help_text='Cydia supports a "More Info" field on the details screen that shunts users off to a website of the packager\'s choice.', null=True, verbose_name='Homepage'),
        ),
        migrations.AlterField(
            model_name='version',
            name='md5',
            field=models.CharField(default='', max_length=32, verbose_name='MD5Sum'),
        ),
        migrations.AlterField(
            model_name='version',
            name='package',
            field=models.CharField(help_text='This is the "identifier" of the package. This should be, entirely in lower case, a reversed hostname (much like a "bundleIdentifier" in Apple\'s Info.plist files).', max_length=255, unique=True, verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='version',
            name='priority',
            field=models.CharField(blank=True, choices=[(None, '-'), ('required', 'Required'), ('standard', 'Standard'), ('optional', 'Optional'), ('extra', 'Extra')], default='', help_text='Sets the importance of this package in relation to the system as a whole.  Common priorities are required, standard, optional, extra, etc.', max_length=255, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='version',
            name='replaces',
            field=models.TextField(blank=True, default='', help_text='List of packages files from which this one replaces. This is used for allowing this package to overwrite the files of another package and is usually used with the Conflicts field to force removal of the other package, if this one also has the same files as the conflicted package.', null=True, verbose_name='Replaces'),
        ),
        migrations.AlterField(
            model_name='version',
            name='size',
            field=models.BigIntegerField(default=0, help_text='The exact size of the package, in bytes.', verbose_name='Size'),
        ),
    ]
