# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0031_auto_20190725_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='gpg_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='GPG Password'),
        ),
    ]
