# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-19 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0034_auto_20170219_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='enable_pdiffs',
            field=models.BooleanField(default=False, help_text='If your package list is extremely large, you should enable this feature to allow incremental update.', verbose_name='Enable pdiffs'),
        ),
    ]
