# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-01 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0034_apple_products_20200301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['-id'], 'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Types'},
        ),
        migrations.AlterModelOptions(
            name='osversion',
            options={'ordering': ['-id'], 'verbose_name': 'iOS Version', 'verbose_name_plural': 'iOS Versions'},
        ),
    ]
