# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0035_setting_enable_pdiffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='enable_pdiffs',
            field=models.BooleanField(default=False, help_text='If package list is extremely large, you should enable this to allow incremental update.', verbose_name='Enable pdiffs'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='packages_validation',
            field=models.IntegerField(choices=[(0, 'No validation'), (1, 'MD5Sum'), (2, 'MD5Sum & SHA1'), (3, 'MD5Sum & SHA1 & SHA256 (Recommended)'), (4, 'MD5Sum & SHA1 & SHA256 & SHA512')], default=3, help_text='You need to update hashes manually.', verbose_name='Packages Validation'),
        ),
    ]
