# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEIPDCRM', '0036_auto_20170220_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='rest_api',
            field=models.BooleanField(default=False, help_text='Upload packages using HTTP, manage your repositories, snapshots, published repositories etc.', verbose_name='REST API'),
        ),
    ]
